name: htcondor-container-build
on: push
jobs:
  build-slurm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          file: Containerfile
          context: .
          push: true
          load: false
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Inspect
        run: |
          docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name}}
          docker image inspect ghcr.io/${{ github.repository }}:${{ github.ref_name}}
